[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
linera-sdk = "0.15.6"
async-trait = "0.1.68"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
async-graphql = "7.0.17"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]